In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[8067, 135, 4239, 9313],
 [8067, 135, 4239, 1382],
 [8067, 3098, 4239, 3179],
 [7249, 4627, 508, 3198, 4903],
 [7249, 4627, 508, 3198, 2710],
 [6971, 8067, 9394, 4239, 2727],
 [176, 1481, 1261, 3198]]

In [8]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8067  135 4239 9313]
 [   0    0    0    0 8067  135 4239 1382]
 [   0    0    0    0 8067 3098 4239 3179]
 [   0    0    0 7249 4627  508 3198 4903]
 [   0    0    0 7249 4627  508 3198 2710]
 [   0    0    0 6971 8067 9394 4239 2727]
 [   0    0    0    0  176 1481 1261 3198]]


In [11]:
## feature representation
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

/opt/anaconda3/envs/mlops/lib/python3.10/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [13]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step


array([[[-0.0239777 ,  0.02726508,  0.03723553,  0.00372796,
          0.02072493,  0.0126592 , -0.00707173, -0.00821612,
         -0.00784976, -0.00113914],
        [-0.0239777 ,  0.02726508,  0.03723553,  0.00372796,
          0.02072493,  0.0126592 , -0.00707173, -0.00821612,
         -0.00784976, -0.00113914],
        [-0.0239777 ,  0.02726508,  0.03723553,  0.00372796,
          0.02072493,  0.0126592 , -0.00707173, -0.00821612,
         -0.00784976, -0.00113914],
        [-0.0239777 ,  0.02726508,  0.03723553,  0.00372796,
          0.02072493,  0.0126592 , -0.00707173, -0.00821612,
         -0.00784976, -0.00113914],
        [ 0.04421022,  0.01091539, -0.00770543, -0.00747959,
         -0.02457299,  0.0115706 ,  0.01981458, -0.03572328,
          0.00341822, -0.00487614],
        [ 0.03013955,  0.01973044, -0.01665433,  0.01521349,
         -0.02525864,  0.01908142,  0.00591341,  0.00864427,
          0.03831651, -0.01001956],
        [ 0.03549435,  0.0333229 ,  0.04691746,  0.0

In [21]:
[embedded_docs[0]]

[array([   0,    0,    0,    0, 8067,  135, 4239, 9313], dtype=int32)]

In [22]:
np.expand_dims(embedded_docs[0], axis=0)

array([[   0,    0,    0,    0, 8067,  135, 4239, 9313]], dtype=int32)

In [23]:
model.predict(np.expand_dims(embedded_docs[0], axis=0))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step


array([[[-0.0239777 ,  0.02726508,  0.03723553,  0.00372796,
          0.02072493,  0.0126592 , -0.00707173, -0.00821612,
         -0.00784976, -0.00113914],
        [-0.0239777 ,  0.02726508,  0.03723553,  0.00372796,
          0.02072493,  0.0126592 , -0.00707173, -0.00821612,
         -0.00784976, -0.00113914],
        [-0.0239777 ,  0.02726508,  0.03723553,  0.00372796,
          0.02072493,  0.0126592 , -0.00707173, -0.00821612,
         -0.00784976, -0.00113914],
        [-0.0239777 ,  0.02726508,  0.03723553,  0.00372796,
          0.02072493,  0.0126592 , -0.00707173, -0.00821612,
         -0.00784976, -0.00113914],
        [ 0.04421022,  0.01091539, -0.00770543, -0.00747959,
         -0.02457299,  0.0115706 ,  0.01981458, -0.03572328,
          0.00341822, -0.00487614],
        [ 0.03013955,  0.01973044, -0.01665433,  0.01521349,
         -0.02525864,  0.01908142,  0.00591341,  0.00864427,
          0.03831651, -0.01001956],
        [ 0.03549435,  0.0333229 ,  0.04691746,  0.0

In [1]:
import tensorflow as tf

# List available devices
print("Num GPUs Available:", len(tf.config.list_physical_devices('GPU')))
print("GPUs:", tf.config.list_physical_devices('GPU'))

# Check if TensorFlow is built with GPU support
print("Built with GPU support:", tf.test.is_built_with_gpu_support())

# Test if TensorFlow can access the GPU
print("Is GPU available:", tf.test.is_gpu_available())

Num GPUs Available: 0
GPUs: []
Built with GPU support: False
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
Is GPU available: False
